# DU-01 — Analyze Source Datasets Structure

**Fase:** Data Understanding  
**Proyecto:** Healthcare AI Billing Auditor  
**Metodología:** ASUM-DM  

Este notebook analiza la estructura de los cinco datasets fuente para comprender su propósito, atributos disponibles, tipos de datos y su papel dentro del sistema automatizado de validación médica.

---
## 1. Configuración

In [5]:
import pandas as pd
import numpy as np
from pathlib import Path

# Configuración de visualización
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)
pd.set_option('display.width', 120)
pd.set_option('display.max_colwidth', 50)

print('Configuración completada.')

Configuración completada.

---
## 2. Carga de Datos

In [23]:
# Ruta base de los datos crudos (modificar si cambia la ubicación)
DATA_RAW_PATH = Path('../data/raw')

# Definición de archivos fuente
DATASET_FILES = {
    'pacientes': '01_pacientes.csv',
    'atenciones': '02_atenciones.csv',
    'historia_clinica': '03_historia_clinica_detalle.csv',
    'prefactura': '04_prefactura.csv',
    'cruce_validacion': '05_cruce_validacion.csv',
}

# Carga de datasets
datasets = {}
for name, filename in DATASET_FILES.items():
    filepath = DATA_RAW_PATH / filename
    datasets[name] = pd.read_csv(filepath)
    print(f'✅ {filename} cargado correctamente — {datasets[name].shape[0]:,} registros, {datasets[name].shape[1]} columnas')

print(f'\nTotal de datasets cargados: {len(datasets)}')

✅ 01_pacientes.csv cargado correctamente — 300 registros, 7 columnas
✅ 02_atenciones.csv cargado correctamente — 1,200 registros, 9 columnas
✅ 03_historia_clinica_detalle.csv cargado correctamente — 3,056 registros, 9 columnas
✅ 04_prefactura.csv cargado correctamente — 2,974 registros, 10 columnas
✅ 05_cruce_validacion.csv cargado correctamente — 3,126 registros, 8 columnas

Total de datasets cargados: 5

---
## 3. Exploración General

### 3.1 Pacientes

Contiene la información demográfica y administrativa de los pacientes atendidos por Health & Life IPS.

In [24]:
df = datasets['pacientes']
print(f'Shape: {df.shape}')
print(f'Registros: {df.shape[0]:,}')
print(f'Columnas: {df.shape[1]}')
print(f'\nColumnas disponibles: {list(df.columns)}')
print(f'\nTipos de datos:')
print(df.dtypes)
df.head()

Shape: (300, 7)
Registros: 300
Columnas: 7

Columnas disponibles: ['id_paciente', 'tipo_documento', 'edad', 'sexo', 'eps', 'tipo_afiliacion', 'ciudad']

Tipos de datos:
id_paciente          str
tipo_documento       str
edad               int64
sexo                 str
eps                  str
tipo_afiliacion      str
ciudad               str
dtype: object

  id_paciente tipo_documento  edad sexo        eps tipo_afiliacion       ciudad
0   PAC-00001             CC    51    M   Coosalud      Subsidiado     Medellin
1   PAC-00002             TI    92    M   Coosalud    Contributivo  Bucaramanga
2   PAC-00003             CC    14    F  Nueva EPS    Contributivo       Bogota
3   PAC-00004             TI    71    M  Famisanar    Contributivo  Bucaramanga
4   PAC-00005             TI    60    F   Sura EPS      Subsidiado  Bucaramanga

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_paciente      300 non-null    str
 1   tipo_documento   300 non-null    str
 2   edad             300 non-null    int64
 3   sexo             300 non-null    str
 4   eps              300 non-null    str
 5   tipo_afiliacion  300 non-null    str
 6   ciudad           300 non-null    str
dtypes: int64(1), str(6)
memory usage: 16.5 KB

### 3.2 Atenciones

Registra cada evento de atención médica prestado a un paciente, incluyendo diagnóstico principal y tipo de atención.

In [26]:
df = datasets['atenciones']
print(f'Shape: {df.shape}')
print(f'Registros: {df.shape[0]:,}')
print(f'Columnas: {df.shape[1]}')
print(f'\nColumnas disponibles: {list(df.columns)}')
print(f'\nTipos de datos:')
print(df.dtypes)
df.head()

Shape: (1200, 9)
Registros: 1,200
Columnas: 9

Columnas disponibles: ['id_atencion', 'id_paciente', 'fecha_atencion', 'tipo_atencion', 'diagnostico_principal_cie10', 'descripcion_diagnostico', 'medico_tratante', 'sede', 'eps']

Tipos de datos:
id_atencion                    str
id_paciente                    str
fecha_atencion                 str
tipo_atencion                  str
diagnostico_principal_cie10    str
descripcion_diagnostico        str
medico_tratante                str
sede                           str
eps                            str
dtype: object

,id_atencion,id_paciente,fecha_atencion,tipo_atencion,diagnostico_principal_cie10,descripcion_diagnostico,medico_tratante,sede,eps
0,ATN-000001,PAC-00295,2026-01-12,Urgencias,I219,"Infarto agudo del miocardio, no especificado",MED-037,Sede Urgencias,Nueva EPS
1,ATN-000002,PAC-00162,2026-04-06,Urgencias,F411,Trastorno de ansiedad generalizada,MED-033,Sede Centro,Sanitas
2,ATN-000003,PAC-00041,2026-05-30,Ambulatoria,O800,Parto único espontáneo,MED-016,Sede Urgencias,Sura EPS
3,ATN-000004,PAC-00079,2025-05-23,Hospitalizacion,Z348,Supervisión de otros embarazos normales,MED-031,Sede Urgencias,Nueva EPS
4,ATN-000005,PAC-00191,2026-06-25,Ambulatoria,N390,"Infección de vías urinarias, sitio no especifi...",MED-008,Sede Sur,Sanitas

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id_atencion                  1200 non-null   str
 1   id_paciente                  1200 non-null   str
 2   fecha_atencion               1200 non-null   str
 3   tipo_atencion                1200 non-null   str
 4   diagnostico_principal_cie10  1200 non-null   str
 5   descripcion_diagnostico      1200 non-null   str
 6   medico_tratante              1200 non-null   str
 7   sede                         1200 non-null   str
 8   eps                          1200 non-null   str
dtypes: str(9)
memory usage: 84.5 KB

### 3.3 Historia Clínica Detalle

Contiene el detalle de procedimientos, consultas, tratamientos y exámenes registrados durante cada atención médica. Es el soporte clínico que justifica la facturación.

In [28]:
df = datasets['historia_clinica']
print(f'Shape: {df.shape}')
print(f'Registros: {df.shape[0]:,}')
print(f'Columnas: {df.shape[1]}')
print(f'\nColumnas disponibles: {list(df.columns)}')
print(f'\nTipos de datos:')
print(df.dtypes)
df.head()

Shape: (3056, 9)
Registros: 3,056
Columnas: 9

Columnas disponibles: ['id_detalle', 'id_atencion', 'tipo_item', 'codigo_cups', 'descripcion', 'cantidad_realizada', 'fecha_registro', 'soporte_clinico', 'profesional_responsable']

Tipos de datos:
id_detalle                   str
id_atencion                  str
tipo_item                    str
codigo_cups                  str
descripcion                  str
cantidad_realizada         int64
fecha_registro               str
soporte_clinico              str
profesional_responsable      str
dtype: object

,id_detalle,id_atencion,tipo_item,codigo_cups,descripcion,cantidad_realizada,fecha_registro,soporte_clinico,profesional_responsable
0,DET-0000001,ATN-000001,consulta,890201,Consulta de primera vez medicina general,1,2026-01-12 06:00,SI,MED-037
1,DET-0000002,ATN-000001,examen,890701,Electrocardiograma,1,2026-01-12 08:00,SI,MED-037
2,DET-0000003,ATN-000001,tratamiento,391201,Angioplastia coronaria,1,2026-01-12 01:00,SI,MED-037
3,DET-0000004,ATN-000002,consulta,890301,Consulta de control por especialista,1,2026-04-06 11:00,SI,MED-033
4,DET-0000005,ATN-000002,tratamiento,990601,Interconsulta psiquiatria,1,2026-04-06 00:00,SI,MED-033

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3056 entries, 0 to 3055
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_detalle               3056 non-null   str
 1   id_atencion              3056 non-null   str
 2   tipo_item                3056 non-null   str
 3   codigo_cups              3056 non-null   str
 4   descripcion              3056 non-null   str
 5   cantidad_realizada       3056 non-null   int64
 6   fecha_registro           3056 non-null   str
 7   soporte_clinico          3056 non-null   str
 8   profesional_responsable  3056 non-null   str
dtypes: int64(1), str(8)
memory usage: 215.0 KB

### 3.4 Pre-factura

Contiene los servicios incluidos en la pre-factura antes de su emisión definitiva. Cada registro representa un procedimiento o servicio que será cobrado.

In [30]:
df = datasets['prefactura']
print(f'Shape: {df.shape}')
print(f'Registros: {df.shape[0]:,}')
print(f'Columnas: {df.shape[1]}')
print(f'\nColumnas disponibles: {list(df.columns)}')
print(f'\nTipos de datos:')
print(df.dtypes)
df.head()

Shape: (2974, 10)
Registros: 2,974
Columnas: 10

Columnas disponibles: ['id_prefactura', 'id_atencion', 'id_paciente', 'codigo_cups_facturado', 'descripcion_servicio_facturado', 'cantidad_facturada', 'valor_unitario', 'valor_total', 'fecha_facturacion', 'eps']

Tipos de datos:
id_prefactura                       str
id_atencion                         str
id_paciente                         str
codigo_cups_facturado               str
descripcion_servicio_facturado      str
cantidad_facturada                int64
valor_unitario                    int64
valor_total                       int64
fecha_facturacion                   str
eps                                 str
dtype: object

,id_prefactura,id_atencion,id_paciente,codigo_cups_facturado,descripcion_servicio_facturado,cantidad_facturada,valor_unitario,valor_total,fecha_facturacion,eps
0,PF-0000001,ATN-000001,PAC-00295,890201,Consulta de primera vez medicina general,1,45000,45000,2026-01-15,Nueva EPS
1,PF-0000002,ATN-000001,PAC-00295,890701,Electrocardiograma,1,38000,38000,2026-01-15,Nueva EPS
2,PF-0000003,ATN-000002,PAC-00162,890301,Consulta de control por especialista,1,90000,90000,2026-04-10,Sanitas
3,PF-0000004,ATN-000002,PAC-00162,990601,Interconsulta psiquiatria,1,130000,130000,2026-04-10,Sanitas
4,PF-0000005,ATN-000003,PAC-00041,890301,Consulta de control por especialista,1,90000,90000,2026-06-03,Sura EPS

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2974 entries, 0 to 2973
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id_prefactura                   2974 non-null   str
 1   id_atencion                     2974 non-null   str
 2   id_paciente                     2974 non-null   str
 3   codigo_cups_facturado           2974 non-null   str
 4   descripcion_servicio_facturado  2974 non-null   str
 5   cantidad_facturada              2974 non-null   int64
 6   valor_unitario                  2974 non-null   int64
 7   valor_total                     2974 non-null   int64
 8   fecha_facturacion               2974 non-null   str
 9   eps                             2974 non-null   str
dtypes: int64(3), str(7)
memory usage: 232.5 KB

### 3.5 Cruce de Validación

Contiene el resultado histórico del proceso de validación entre Historia Clínica y Pre-factura. Sirve como ground truth para evaluar y entrenar el modelo de IA.

In [32]:
df = datasets['cruce_validacion']
print(f'Shape: {df.shape}')
print(f'Registros: {df.shape[0]:,}')
print(f'Columnas: {df.shape[1]}')
print(f'\nColumnas disponibles: {list(df.columns)}')
print(f'\nTipos de datos:')
print(df.dtypes)
df.head()

Shape: (3126, 8)
Registros: 3,126
Columnas: 8

Columnas disponibles: ['id_cruce', 'id_atencion', 'id_prefactura', 'id_detalle_hc', 'resultado', 'tipo_alerta', 'severidad', 'descripcion_alerta']

Tipos de datos:
id_cruce              str
id_atencion           str
id_prefactura         str
id_detalle_hc         str
resultado             str
tipo_alerta           str
severidad             str
descripcion_alerta    str
dtype: object

,id_cruce,id_atencion,id_prefactura,id_detalle_hc,resultado,tipo_alerta,severidad,descripcion_alerta
0,CRZ-0000001,ATN-000001,PF-0000001,DET-0000001,INCONSISTENTE,DIAGNOSTICO_NO_RELACIONADO,MEDIA,El diagnostico principal no justifica el servi...
1,CRZ-0000002,ATN-000001,PF-0000002,DET-0000002,INCONSISTENTE,DIAGNOSTICO_NO_RELACIONADO,MEDIA,El diagnostico principal no justifica el servi...
2,CRZ-0000003,ATN-000001,NaN,DET-0000003,INCONSISTENTE,NO_FACTURADO,ALTA,Procedimiento con soporte clinico que no fue f...
3,CRZ-0000004,ATN-000002,PF-0000003,DET-0000004,CONSISTENTE,CONSISTENTE,NINGUNA,"Coincide cantidad, codigo y soporte clinico"
4,CRZ-0000005,ATN-000002,PF-0000004,DET-0000005,CONSISTENTE,CONSISTENTE,NINGUNA,"Coincide cantidad, codigo y soporte clinico"

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3126 entries, 0 to 3125
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_cruce            3126 non-null   str
 1   id_atencion         3126 non-null   str
 2   id_prefactura       2974 non-null   str
 3   id_detalle_hc       3056 non-null   str
 4   resultado           3126 non-null   str
 5   tipo_alerta         3126 non-null   str
 6   severidad           3126 non-null   str
 7   descripcion_alerta  3126 non-null   str
dtypes: str(8)
memory usage: 195.5 KB

---
## 4. Identificación de Identificadores

In [34]:
# Definición de llaves basada en la arquitectura de datos (AA-02)
KEYS_MAP = {
    'pacientes': {
        'primary_key': 'id_paciente',
        'foreign_keys': []
    },
    'atenciones': {
        'primary_key': 'id_atencion',
        'foreign_keys': ['id_paciente']
    },
    'historia_clinica': {
        'primary_key': 'id_detalle',
        'foreign_keys': ['id_atencion']
    },
    'prefactura': {
        'primary_key': 'id_prefactura',
        'foreign_keys': ['id_atencion', 'id_paciente']
    },
    'cruce_validacion': {
        'primary_key': 'id_cruce',
        'foreign_keys': ['id_atencion', 'id_prefactura', 'id_detalle_hc']
    }
}

print('Análisis de identificadores por dataset:\n')
for name, keys in KEYS_MAP.items():
    df = datasets[name]
    pk = keys['primary_key']
    pk_unique = df[pk].nunique()
    pk_total = len(df)
    is_unique = pk_unique == pk_total
    
    print(f'📋 {name.upper()}')
    print(f'   Primary Key: {pk}')
    print(f'   Valores únicos: {pk_unique:,} / {pk_total:,} ({"✅ Única" if is_unique else "⚠️ No única"})')
    
    if keys['foreign_keys']:
        print(f'   Foreign Keys: {", ".join(keys["foreign_keys"])}')
        for fk in keys['foreign_keys']:
            if fk in df.columns:
                fk_unique = df[fk].nunique()
                fk_nulls = df[fk].isnull().sum()
                print(f'     - {fk}: {fk_unique:,} valores únicos, {fk_nulls} nulos')
            else:
                print(f'     - {fk}: ⚠️ COLUMNA NO ENCONTRADA')
    print()

Análisis de identificadores por dataset:

📋 PACIENTES
   Primary Key: id_paciente
   Valores únicos: 300 / 300 (✅ Única)

📋 ATENCIONES
   Primary Key: id_atencion
   Valores únicos: 1,200 / 1,200 (✅ Única)
   Foreign Keys: id_paciente
     - id_paciente: 293 valores únicos, 0 nulos

📋 HISTORIA_CLINICA
   Primary Key: id_detalle
   Valores únicos: 3,056 / 3,056 (✅ Única)
   Foreign Keys: id_atencion
     - id_atencion: 1,200 valores únicos, 0 nulos

📋 PREFACTURA
   Primary Key: id_prefactura
   Valores únicos: 2,974 / 2,974 (✅ Única)
   Foreign Keys: id_atencion, id_paciente
     - id_atencion: 1,200 valores únicos, 0 nulos
     - id_paciente: 293 valores únicos, 0 nulos

📋 CRUCE_VALIDACION
   Primary Key: id_cruce
   Valores únicos: 3,126 / 3,126 (✅ Única)
   Foreign Keys: id_atencion, id_prefactura, id_detalle_hc
     - id_atencion: 1,200 valores únicos, 0 nulos
     - id_prefactura: 2,974 valores únicos, 152 nulos
     - id_detalle_hc: 3,056 valores únicos, 70 nulos

---
## 5. Calidad Básica de Datos

In [18]:
def analyze_data_quality(df, name):
    """Genera un reporte de calidad básica para un DataFrame."""
    print(f'\n{"=" * 60}')
    print(f'📊 CALIDAD DE DATOS — {name.upper()}')
    print(f'{"=" * 60}')
    
    # Valores nulos
    nulls = df.isnull().sum()
    null_pct = (df.isnull().sum() / len(df) * 100).round(2)
    
    print(f'\n--- Valores Nulos ---')
    null_report = pd.DataFrame({
        'nulos': nulls,
        'porcentaje': null_pct
    })
    print(null_report[null_report['nulos'] > 0].to_string() if null_report['nulos'].sum() > 0 else '  Sin valores nulos ✅')
    
    # Valores únicos
    print(f'\n--- Valores Únicos ---')
    unique_report = pd.DataFrame({
        'unicos': df.nunique(),
        'total': len(df),
        'pct_unico': (df.nunique() / len(df) * 100).round(2)
    })
    print(unique_report.to_string())
    
    # Duplicados
    duplicates = df.duplicated().sum()
    print(f'\n--- Duplicados ---')
    print(f'  Filas duplicadas: {duplicates:,} ({duplicates / len(df) * 100:.2f}%)')
    
    # Memoria
    memory_mb = df.memory_usage(deep=True).sum() / 1024 / 1024
    print(f'\n--- Memoria ---')
    print(f'  Uso de memoria: {memory_mb:.2f} MB')
    
    return null_report

In [19]:
quality_reports = {}
for name, df in datasets.items():
    quality_reports[name] = analyze_data_quality(df, name)

============================================================
📊 CALIDAD DE DATOS — PACIENTES
============================================================

--- Valores Nulos ---
  Sin valores nulos ✅

--- Valores Únicos ---
                 unicos  total  pct_unico
id_paciente         300    300     100.00
tipo_documento        4    300       1.33
edad                 93    300      31.00
sexo                  2    300       0.67
eps                   6    300       2.00
tipo_afiliacion       2    300       0.67
ciudad                5    300       1.67

--- Duplicados ---
  Filas duplicadas: 0 (0.00%)

--- Memoria ---
  Uso de memoria: 0.11 MB

============================================================
📊 CALIDAD DE DATOS — ATENCIONES
============================================================

--- Valores Nulos ---
  Sin valores nulos ✅

--- Valores Únicos ---
                             unicos  total  pct_unico
id_atencion                    1200   1200     100.00
id_paciente                     293   1200      24.42
fecha_atencion                  488   1200      40.67
tipo_atencion                     3   1200       0.25
diagnostico_principal_cie10      15   1200       1.25
descripcion_diagnostico          15   1200       1.25
medico_tratante                  40   1200       3.33
sede                              4   1200       0.33
eps                               6   1200       0.50

--- Duplicados ---
  Filas duplicadas: 0 (0.00%)

--- Memoria ---
  Uso de memoria: 0.73 MB

============================================================
📊 CALIDAD DE DATOS — HISTORIA_CLINICA
============================================================

--- Valores Nulos ---
  Sin valores nulos ✅

--- Valores Únicos ---
                         unicos  total  pct_unico
id_detalle                 3056   3056     100.00
id_atencion                1200   3056      39.27
tipo_item                     3   3056       0.10
codigo_cups                  18   3056       0.59
descripcion                  18   3056       0.59
cantidad_realizada            2   3056       0.07
fecha_registro             2562   3056      83.84
soporte_clinico               1   3056       0.03
profesional_responsable      40   3056       1.31

--- Duplicados ---
  Filas duplicadas: 0 (0.00%)

--- Memoria ---
  Uso de memoria: 1.61 MB

============================================================
📊 CALIDAD DE DATOS — PREFACTURA
============================================================

--- Valores Nulos ---
  Sin valores nulos ✅

--- Valores Únicos ---
                                unicos  total  pct_unico
id_prefactura                     2974   2974     100.00
id_atencion                       1200   2974      40.35
id_paciente                        293   2974       9.85
codigo_cups_facturado               18   2974       0.61
descripcion_servicio_facturado      18   2974       0.61
cantidad_facturada                   4   2974       0.13
valor_unitario                      18   2974       0.61
valor_total                         44   2974       1.48
fecha_facturacion                  488   2974      16.41
eps                                  6   2974       0.20

--- Duplicados ---
  Filas duplicadas: 0 (0.00%)

--- Memoria ---
  Uso de memoria: 1.43 MB

============================================================
📊 CALIDAD DE DATOS — CRUCE_VALIDACION
============================================================

--- Valores Nulos ---
               nulos  porcentaje
id_prefactura    152        4.86
id_detalle_hc     70        2.24

--- Valores Únicos ---
                    unicos  total  pct_unico
id_cruce              3126   3126     100.00
id_atencion           1200   3126      38.39
id_prefactura         2974   3126      95.14
id_detalle_hc         3056   3126      97.76
resultado                2   3126       0.06
tipo_alerta              6   3126       0.19
severidad                3   3126       0.10
descripcion_alerta       6   3126       0.19

--- Duplicados ---
  Filas duplicadas: 0 (0.00%)

--- Memoria ---
  Uso de memoria: 1.71 MB

---
## 6. Resumen Estructural

In [20]:
# Descripciones de cada dataset según la arquitectura de datos
DESCRIPTIONS = {
    'pacientes': 'Información demográfica y administrativa de los pacientes.',
    'atenciones': 'Registro de cada atención médica realizada al paciente.',
    'historia_clinica': 'Detalle de procedimientos, tratamientos y exámenes registrados durante la atención.',
    'prefactura': 'Servicios incluidos en la pre-factura antes de su emisión definitiva.',
    'cruce_validacion': 'Resultado histórico del cruce de validación entre Historia Clínica y Pre-factura.'
}

# Generar tabla resumen
summary_rows = []
for name, df in datasets.items():
    keys = KEYS_MAP[name]
    summary_rows.append({
        'Dataset': name,
        'Archivo': DATASET_FILES[name],
        'Registros': f'{df.shape[0]:,}',
        'Columnas': df.shape[1],
        'Primary Key': keys['primary_key'],
        'Foreign Keys': ', '.join(keys['foreign_keys']) if keys['foreign_keys'] else '—',
        'Descripción': DESCRIPTIONS[name]
    })

summary_df = pd.DataFrame(summary_rows)
summary_df

,Dataset,Archivo,Registros,Columnas,Primary Key,Foreign Keys,Descripción
0,pacientes,01_pacientes.csv,300,7,id_paciente,—,Información demográfica y administrativa de lo...
1,atenciones,02_atenciones.csv,"1,200",9,id_atencion,id_paciente,Registro de cada atención médica realizada al ...
2,historia_clinica,03_historia_clinica_detalle.csv,"3,056",9,id_detalle,id_atencion,"Detalle de procedimientos, tratamientos y exám..."
3,prefactura,04_prefactura.csv,"2,974",10,id_prefactura,"id_atencion, id_paciente",Servicios incluidos en la pre-factura antes de...
4,cruce_validacion,05_cruce_validacion.csv,"3,126",8,id_cruce,"id_atencion, id_prefactura, id_detalle_hc",Resultado histórico del cruce de validación en...

In [35]:
# Resumen de calidad consolidado
quality_summary_rows = []
for name, df in datasets.items():
    total_nulls = df.isnull().sum().sum()
    total_cells = df.shape[0] * df.shape[1]
    duplicates = df.duplicated().sum()
    memory_mb = df.memory_usage(deep=True).sum() / 1024 / 1024
    
    quality_summary_rows.append({
        'Dataset': name,
        'Registros': f'{df.shape[0]:,}',
        'Nulos Totales': f'{total_nulls:,}',
        'Pct Nulos': f'{total_nulls / total_cells * 100:.2f}%',
        'Duplicados': f'{duplicates:,}',
        'Memoria (MB)': f'{memory_mb:.2f}'
    })

quality_summary_df = pd.DataFrame(quality_summary_rows)
quality_summary_df

            Dataset Registros Nulos Totales Pct Nulos Duplicados Memoria (MB)
0         pacientes       300             0     0.00%          0         0.11
1        atenciones     1,200             0     0.00%          0         0.73
2  historia_clinica     3,056             0     0.00%          0         1.61
3        prefactura     2,974             0     0.00%          0         1.43
4  cruce_validacion     3,126           222     0.89%          0         1.71

---
## 7. Observaciones

### 7.1 Pacientes (`01_pacientes.csv`)

- **Representa:** Información demográfica y administrativa de los pacientes.
- **Aporta al sistema:** Datos contextuales del paciente (edad, sexo, EPS, tipo de afiliación, ciudad) que permiten segmentar análisis y evaluar posibles sesgos del modelo.
- **Relación:** Es la entidad raíz. Se conecta con `atenciones` y `prefactura` mediante `id_paciente`.

### 7.2 Atenciones (`02_atenciones.csv`)

- **Representa:** Cada evento de servicio de salud prestado a un paciente.
- **Aporta al sistema:** El diagnóstico principal (CIE-10), tipo de atención, fecha y sede. Estos datos son fundamentales para validar la coherencia entre diagnóstico y procedimientos.
- **Relación:** Conecta pacientes con sus registros clínicos y de facturación. Es la tabla pivote del modelo de datos (FK: `id_paciente`; referenciada por: `historia_clinica`, `prefactura`, `cruce_validacion`).

### 7.3 Historia Clínica Detalle (`03_historia_clinica_detalle.csv`)

- **Representa:** El detalle de procedimientos, consultas, tratamientos y exámenes registrados durante cada atención.
- **Aporta al sistema:** Es el soporte clínico que debe justificar cada cobro en la pre-factura. Contiene `codigo_cups`, `tipo_item`, `cantidad_realizada` y `soporte_clinico`.
- **Relación:** Se vincula a `atenciones` mediante `id_atencion`. Cada atención puede tener múltiples registros clínicos.

### 7.4 Pre-factura (`04_prefactura.csv`)

- **Representa:** Los servicios y procedimientos que serán cobrados antes de emitir la factura definitiva.
- **Aporta al sistema:** Contiene `codigo_cups_facturado`, `cantidad_facturada`, `valor_unitario` y `valor_total`. Estos campos se comparan contra la Historia Clínica para detectar inconsistencias.
- **Relación:** Se vincula a `atenciones` y `pacientes` mediante `id_atencion` e `id_paciente`.

### 7.5 Cruce de Validación (`05_cruce_validacion.csv`)

- **Representa:** El resultado histórico de la validación entre Historia Clínica y Pre-factura.
- **Aporta al sistema:** Funciona como ground truth para entrenamiento y evaluación del modelo de IA. Contiene `resultado`, `tipo_alerta` y `severidad`.
- **Relación:** Conecta `atenciones`, `prefactura` e `historia_clinica` mediante `id_atencion`, `id_prefactura` e `id_detalle_hc`.

---
## Conclusión

Los cinco datasets fueron cargados y analizados estructuralmente. Se identificaron:
- Las llaves primarias y foráneas de cada dataset.
- El volumen de registros y columnas.
- La calidad básica (nulos, duplicados, memoria).
- El propósito de cada dataset dentro del sistema de validación.

**Siguiente paso:** Análisis exploratorio detallado de cada variable (DU-02).