In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
os.chdir("/home/antoniog/Documentos/SIC_2026/Capstone")

In [4]:
pacientes = pd.read_csv("01_pacientes.csv")

In [5]:
pacientes.head()

,id_paciente,tipo_documento,edad,sexo,eps,tipo_afiliacion,ciudad
0,PAC-00001,CC,51,M,Coosalud,Subsidiado,Medellin
1,PAC-00002,TI,92,M,Coosalud,Contributivo,Bucaramanga
2,PAC-00003,CC,14,F,Nueva EPS,Contributivo,Bogota
3,PAC-00004,TI,71,M,Famisanar,Contributivo,Bucaramanga
4,PAC-00005,TI,60,F,Sura EPS,Subsidiado,Bucaramanga

In [6]:
len(pacientes['id_paciente'].unique())

300

In [7]:
pacientes['sexo'].value_counts()

sexo
F    164
M    136
Name: count, dtype: int64

In [8]:
pacientes.eps.value_counts()

eps
Nueva EPS    68
Coosalud     54
Compensar    52
Famisanar    44
Sanitas      43
Sura EPS     39
Name: count, dtype: int64

In [9]:
pacientes.tipo_afiliacion.value_counts()

tipo_afiliacion
Contributivo    151
Subsidiado      149
Name: count, dtype: int64

In [10]:
atenciones = pd.read_csv("02_atenciones.csv")

In [11]:
atenciones

,id_atencion,id_paciente,fecha_atencion,tipo_atencion,diagnostico_principal_cie10,descripcion_diagnostico,medico_tratante,sede,eps
0,ATN-000001,PAC-00295,2026-01-12,Urgencias,I219,"Infarto agudo del miocardio, no especificado",MED-037,Sede Urgencias,Nueva EPS
1,ATN-000002,PAC-00162,2026-04-06,Urgencias,F411,Trastorno de ansiedad generalizada,MED-033,Sede Centro,Sanitas
2,ATN-000003,PAC-00041,2026-05-30,Ambulatoria,O800,Parto único espontáneo,MED-016,Sede Urgencias,Sura EPS
3,ATN-000004,PAC-00079,2025-05-23,Hospitalizacion,Z348,Supervisión de otros embarazos normales,MED-031,Sede Urgencias,Nueva EPS
4,ATN-000005,PAC-00191,2026-06-25,Ambulatoria,N390,"Infección de vías urinarias, sitio no especifi...",MED-008,Sede Sur,Sanitas
...,...,...,...,...,...,...,...,...,...
1195,ATN-001196,PAC-00287,2026-03-22,Hospitalizacion,M545,Lumbago no especificado,MED-026,Sede Sur,Sanitas
1196,ATN-001197,PAC-00066,2026-03-13,Urgencias,C349,Tumor maligno del bronquio o del pulmón,MED-003,Sede Sur,Famisanar
1197,ATN-001198,PAC-00083,2025-10-06,Urgencias,A090,Diarrea y gastroenteritis de presunto origen i...,MED-028,Sede Centro,Coosalud
1198,ATN-001199,PAC-00068,2026-04-23,Urgencias,C349,Tumor maligno del bronquio o del pulmón,MED-001,Sede Centro,Sanitas
1199,ATN-001200,PAC-00219,2025-11-18,Hospitalizacion,A090,Diarrea y gastroenteritis de presunto origen i...,MED-019,Sede Sur,Nueva EPS

In [12]:
atenciones['tipo_atencion'].value_counts()

tipo_atencion
Urgencias          421
Ambulatoria        407
Hospitalizacion    372
Name: count, dtype: int64

In [13]:
atenciones['diagnostico_principal_cie10'].value_counts()

diagnostico_principal_cie10
M545    95
H269    94
I219    89
J189    87
K358    84
R073    83
I10X    83
Z348    81
E119    81
N390    76
S824    73
C349    72
O800    71
A090    68
F411    63
Name: count, dtype: int64

In [14]:
len(atenciones['medico_tratante'].value_counts())

40

In [15]:
atenciones['sede'].value_counts()

sede
Sede Urgencias    325
Sede Norte        307
Sede Centro       293
Sede Sur          275
Name: count, dtype: int64

In [16]:
hist = pd.read_csv("03_historia_clinica_detalle.csv")

In [68]:
hist

,id_detalle_hc,id_atencion,tipo_item,codigo_cups,descripcion,cantidad_realizada,fecha_registro,soporte_clinico,profesional_responsable
0,DET-0000001,ATN-000001,consulta,890201,Consulta de primera vez medicina general,1,2026-01-12 06:00,SI,MED-037
1,DET-0000002,ATN-000001,examen,890701,Electrocardiograma,1,2026-01-12 08:00,SI,MED-037
2,DET-0000003,ATN-000001,tratamiento,391201,Angioplastia coronaria,1,2026-01-12 01:00,SI,MED-037
3,DET-0000004,ATN-000002,consulta,890301,Consulta de control por especialista,1,2026-04-06 11:00,SI,MED-033
4,DET-0000005,ATN-000002,tratamiento,990601,Interconsulta psiquiatria,1,2026-04-06 00:00,SI,MED-033
...,...,...,...,...,...,...,...,...,...
3051,DET-0003052,ATN-001199,examen,871111,Radiografia de torax,2,2026-04-23 13:00,SI,MED-001
3052,DET-0003053,ATN-001199,examen,930601,Tomografia axial computarizada de torax,1,2026-04-23 13:00,SI,MED-001
3053,DET-0003054,ATN-001200,consulta,890301,Consulta de control por especialista,1,2025-11-18 13:00,SI,MED-019
3054,DET-0003055,ATN-001200,tratamiento,890201-M,Terapia de rehidratacion oral supervisada,1,2025-11-18 07:00,SI,MED-019
3055,DET-0003056,ATN-001200,examen,902210,Hemograma completo,1,2025-11-18 10:00,SI,MED-019

In [18]:
hist.groupby(['codigo_cups', 'descripcion']).size().sort_values(ascending=False)

codigo_cups  descripcion
890415       Control prenatal                             560
890201       Consulta de primera vez medicina general     474
890301       Consulta de control por especialista         458
902210       Hemograma completo                           281
890701       Electrocardiograma                           199
871111       Radiografia de torax                         170
881201       Ecografia abdominal total                    125
881332       Ecografia obstetrica                         111
930601       Tomografia axial computarizada de torax       96
391013       Facoemulsificacion con lente intraocular      94
930878       Reduccion cerrada de fractura de peroné       73
391121       Apendicectomia                                65
903841       Glicemia basal                                65
391201       Angioplastia coronaria                        63
990601       Interconsulta psiquiatria                     63
903875       Parcial de orina                              61
890201-M     Terapia de rehidratacion oral supervisada     52
739001       Atencion del parto                            46
dtype: int64

In [19]:
prefactura = pd.read_csv("04_prefactura.csv")

In [20]:
prefactura.head()

,id_prefactura,id_atencion,id_paciente,codigo_cups_facturado,descripcion_servicio_facturado,cantidad_facturada,valor_unitario,valor_total,fecha_facturacion,eps
0,PF-0000001,ATN-000001,PAC-00295,890201,Consulta de primera vez medicina general,1,45000,45000,2026-01-15,Nueva EPS
1,PF-0000002,ATN-000001,PAC-00295,890701,Electrocardiograma,1,38000,38000,2026-01-15,Nueva EPS
2,PF-0000003,ATN-000002,PAC-00162,890301,Consulta de control por especialista,1,90000,90000,2026-04-10,Sanitas
3,PF-0000004,ATN-000002,PAC-00162,990601,Interconsulta psiquiatria,1,130000,130000,2026-04-10,Sanitas
4,PF-0000005,ATN-000003,PAC-00041,890301,Consulta de control por especialista,1,90000,90000,2026-06-03,Sura EPS

In [21]:
validacion = pd.read_csv("05_cruce_validacion.csv")

In [22]:
validacion.head()

,id_cruce,id_atencion,id_prefactura,id_detalle_hc,resultado,tipo_alerta,severidad,descripcion_alerta
0,CRZ-0000001,ATN-000001,PF-0000001,DET-0000001,INCONSISTENTE,DIAGNOSTICO_NO_RELACIONADO,MEDIA,El diagnostico principal no justifica el servi...
1,CRZ-0000002,ATN-000001,PF-0000002,DET-0000002,INCONSISTENTE,DIAGNOSTICO_NO_RELACIONADO,MEDIA,El diagnostico principal no justifica el servi...
2,CRZ-0000003,ATN-000001,NaN,DET-0000003,INCONSISTENTE,NO_FACTURADO,ALTA,Procedimiento con soporte clinico que no fue f...
3,CRZ-0000004,ATN-000002,PF-0000003,DET-0000004,CONSISTENTE,CONSISTENTE,NINGUNA,"Coincide cantidad, codigo y soporte clinico"
4,CRZ-0000005,ATN-000002,PF-0000004,DET-0000005,CONSISTENTE,CONSISTENTE,NINGUNA,"Coincide cantidad, codigo y soporte clinico"

In [23]:
tablas = [pacientes, atenciones, hist, prefactura, validacion]

In [24]:
validacion['descripcion_alerta'].unique()

<ArrowStringArray>
[             'El diagnostico principal no justifica el servicio facturado',
 'Procedimiento con soporte clinico que no fue facturado (fuga de ingreso)',
                              'Coincide cantidad, codigo y soporte clinico',
            'Cantidad facturada difiere de la cantidad registrada en la HC',
              'Servicio facturado sin registro de soporte clinico en la HC',
       'El codigo CUPS facturado no corresponde al procedimiento realizado']
Length: 6, dtype: str

In [25]:
validacion.query("descripcion_alerta == 'Servicio facturado sin registro de soporte clinico en la HC'")

,id_cruce,id_atencion,id_prefactura,id_detalle_hc,resultado,tipo_alerta,severidad,descripcion_alerta
20,CRZ-0000021,ATN-000008,PF-0000020,DET-0000021,INCONSISTENTE,SIN_SOPORTE_CLINICO,ALTA,Servicio facturado sin registro de soporte cli...
22,CRZ-0000023,ATN-000008,PF-0000022,NaN,INCONSISTENTE,SIN_SOPORTE_CLINICO,ALTA,Servicio facturado sin registro de soporte cli...
67,CRZ-0000068,ATN-000028,PF-0000062,DET-0000067,INCONSISTENTE,SIN_SOPORTE_CLINICO,ALTA,Servicio facturado sin registro de soporte cli...
115,CRZ-0000116,ATN-000045,PF-0000108,DET-0000115,INCONSISTENTE,SIN_SOPORTE_CLINICO,ALTA,Servicio facturado sin registro de soporte cli...
116,CRZ-0000117,ATN-000045,PF-0000109,DET-0000116,INCONSISTENTE,SIN_SOPORTE_CLINICO,ALTA,Servicio facturado sin registro de soporte cli...
...,...,...,...,...,...,...,...,...
3054,CRZ-0003055,ATN-001171,PF-0002905,DET-0002987,INCONSISTENTE,SIN_SOPORTE_CLINICO,ALTA,Servicio facturado sin registro de soporte cli...
3057,CRZ-0003058,ATN-001171,PF-0002908,NaN,INCONSISTENTE,SIN_SOPORTE_CLINICO,ALTA,Servicio facturado sin registro de soporte cli...
3088,CRZ-0003089,ATN-001185,PF-0002938,DET-0003020,INCONSISTENTE,SIN_SOPORTE_CLINICO,ALTA,Servicio facturado sin registro de soporte cli...
3089,CRZ-0003090,ATN-001185,PF-0002939,DET-0003021,INCONSISTENTE,SIN_SOPORTE_CLINICO,ALTA,Servicio facturado sin registro de soporte cli...
3125,CRZ-0003126,ATN-001200,PF-0002974,NaN,INCONSISTENTE,SIN_SOPORTE_CLINICO,ALTA,Servicio facturado sin registro de soporte cli...

In [69]:
for i in range(len(tablas)):
    print(f"Tabla {i+1}:")
    print(pd.DataFrame(tablas[i].columns))
    print("\n")

Tabla 1:
                 0
0      id_paciente
1   tipo_documento
2             edad
3             sexo
4              eps
5  tipo_afiliacion
6           ciudad


Tabla 2:
                             0
0                  id_atencion
1                  id_paciente
2               fecha_atencion
3                tipo_atencion
4  diagnostico_principal_cie10
5      descripcion_diagnostico
6              medico_tratante
7                         sede
8                          eps


Tabla 3:
                         0
0            id_detalle_hc
1              id_atencion
2                tipo_item
3              codigo_cups
4              descripcion
5       cantidad_realizada
6           fecha_registro
7          soporte_clinico
8  profesional_responsable


Tabla 4:
                                0
0                   id_prefactura
1                     id_atencion
2                     id_paciente
3           codigo_cups_facturado
4  descripcion_servicio_facturado
5              cantidad_facturada
6                  valor_unitario
7                     valor_total
8               fecha_facturacion
9                             eps


Tabla 5:
                    0
0            id_cruce
1         id_atencion
2       id_prefactura
3       id_detalle_hc
4           resultado
5         tipo_alerta
6           severidad
7  descripcion_alerta

In [60]:
tablas[0]

,id_paciente,tipo_documento,edad,sexo,eps,tipo_afiliacion,ciudad
0,PAC-00001,CC,51,M,Coosalud,Subsidiado,Medellin
1,PAC-00002,TI,92,M,Coosalud,Contributivo,Bucaramanga
2,PAC-00003,CC,14,F,Nueva EPS,Contributivo,Bogota
3,PAC-00004,TI,71,M,Famisanar,Contributivo,Bucaramanga
4,PAC-00005,TI,60,F,Sura EPS,Subsidiado,Bucaramanga
...,...,...,...,...,...,...,...
295,PAC-00296,CC,83,F,Famisanar,Contributivo,Bucaramanga
296,PAC-00297,RC,88,M,Sura EPS,Contributivo,Bucaramanga
297,PAC-00298,TI,24,F,Nueva EPS,Subsidiado,Cali
298,PAC-00299,TI,92,F,Famisanar,Subsidiado,Barranquilla
299,PAC-00300,TI,17,M,Sanitas,Subsidiado,Medellin